version: '3'
services:
  hugo:
    image: klakegg/hugo:ext-ubuntu
    volumes:
      - ../src:/usr/src
    working_dir: /usr/src
    environment:
      - TZ=Asia/Tokyo
    entrypoint: bash
    tty: true
